### ISSUE TITLE
Add copy to clipboard option to shared options on desktop

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie-web#118]
Shared options does not have copy to image

**Comment by ojulianos** [comment]
![Screen Shot 2021-02-17 at 00 06 30](https://user-images.githubusercontent.com/16178196/108150774-01b51180-70b4-11eb-9014-af89db5faf76.png)

This is to add a copy option here ?

**Comment by deven96** [comment]
Yes it is @ojulianos
