### ISSUE TITLE
(Year, Category) Filters

### ISSUE THREAD

**Issue by silvareal** [Go-phie/gophie-web#46]
Filters a movie slection based of it's **year** or   **category**

**Comment by deven96** [comment]
Hmmm, we are not assured this info comes with every movie
Year perhaps but there is no category

**Comment by silvareal** [comment]
we will work on the year filters for  now, pending when or if the category schema will be ready.

If the year  of a movie is not avilable, we will fallback to a default year

**Comment by Amenacliff** [comment]
Can I work on this?

**Comment by deven96** [comment]
> Can I work on this?

What do you think @silvareal I know you're quite busy with other features so can @Amenacliff work on the filter by year?. Note: some movie objects come back without a year  so have that in mind

**Comment by silvareal** [comment]
Ok, @Amenacliff  you can go ahead.

**Comment by Amenacliff** [comment]
> Ok, @Amenacliff  you can go ahead.

Kindly Assign me to the Project

**Comment by Amenacliff** [comment]
So according to the Contribution.md we will have to discuss this.

#Should we have a filter Icon that takes the year input of a user and then we filter the movies based on the year given?

Or should we have an Option section where the year is selected?

Personally I prefer the first one what do you think?

**Comment by deven96** [comment]
> So according to the Contribution.md we will have to discuss this.
> 
> #Should we have a filter Icon that takes the year input of a user and then we filter the movies based on the year given?
> 
> Or should we have an Option section where the year is selected?
> 
> Personally I prefer the first one what do you think?

Go ahead with the first one

**Comment by silvareal** [comment]
Go ahead with the first one, with its universal icon

**Comment by Amenacliff** [comment]
After Looking critically at this issue I realize that the search bar at the top can carry out that function.

E.g search 2019 in the search bar gives the movies from 2019

Hence we don't need another search bar or function to search.

**Comment by silvareal** [comment]
yhp great, just realised that too, we need a way to tell the user about this, @deven96 what do you think?

**Comment by Amenacliff** [comment]
> yhp great, just realised that too, we need a way to tell the user about this, @deven96 what do you think?

I think we can add that to the tour.

Would that be great?

**Comment by deven96** [comment]
Wouldn't that conflict with maybe if there is actually a movie called 2019?
How do we differentiate between 4 digit movie names and years?

**Comment by silvareal** [comment]
Great perspective, It's a tricky situation even, because the search is by **movie titles**,
while some movies title have a _suffix_ of year

> _e.g money heist 2019_

some of them dont.

It will be great if the filter is explicity created.

**Comment by silvareal** [comment]
@Amenacliff you can go ahead with the filter, It is an essential feature for a good UX.

**Comment by deven96** [comment]
> Great perspective, It's a tricky situation even, because the search is by **movie titles**,
> while some movies title have a _suffix_ of year
> 
> > _e.g money heist 2019_
> 
> some of them dont.
> 
> It will be great if the filter is explicity created.

Exactly, an explicit filter would be better

**Comment by Amenacliff** [comment]
Does your API have a year query?

Because the movie props passed to the Movie  Component just gives off the data gotten from  the fetch done by axios.

**Comment by deven96** [comment]
> Does your API have a year query?
> 
> Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.

It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field

**Comment by silvareal** [comment]
@deven96 I just realized, we do have a year query.

@Amenacliff  this should give you a headstart [Goophie api](https://gophie.herokuapp.com/list?page=1&engine=netnaija)

**Comment by Amenacliff** [comment]
> @deven96 I just realized, we do have a year query.
> 
> @Amenacliff  this should give you a headstart [Goophie api](https://gophie.herokuapp.com/list?page=1&engine=netnaija)

Okay nice

**Comment by Amenacliff** [comment]
> > Does your API have a year query?
> > 
> > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> 
> It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field

I think it can be done.


From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.

If we are trying to filter from the movie props sent to the  Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.

So Imagine a situation where a user doesn't scroll to the bottom and the movie  "year"  searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.

So we need to find a way to pass all the movies without pagination so we can filter through all the movies.

That's how we can do this

Hope you understand?

**Comment by Amenacliff** [comment]
> > > Does your API have a year query?
> > > 
> > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > 
> > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> 
> I think it can be done.
> 
> 
> From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> 
> If we are trying to filter from the movie props sent to the  Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> 
> So Imagine a situation where a user doesn't scroll to the bottom and the movie  "year"  searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> 
> So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> 
> That's how we can do this
> 
> Hope you understand?

Solved it 😅😅 will be sending a pull request soon

**Comment by silvareal** [comment]
> > > Does your API have a year query?
> > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > 
> > 
> > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> 
> I think it can be done.
> 
> From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> 
> If we are trying to filter from the movie props sent to the Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> 
> So Imagine a situation where a user doesn't scroll to the bottom and the movie "year" searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> 
> So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> 
> That's how we can do this
> 
> Hope you understand?

> > > > Does your API have a year query?
> > > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > > 
> > > 
> > > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> > 
> > 
> > I think it can be done.
> > From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> > If we are trying to filter from the movie props sent to the  Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> > So Imagine a situation where a user doesn't scroll to the bottom and the movie  "year"  searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> > So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> > That's how we can do this
> > Hope you understand?
> 
> Solved it 😅😅 will be sending a pull request soon

Great

**Comment by Amenacliff** [comment]
> > > > Does your API have a year query?
> > > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > > 
> > > 
> > > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> > 
> > I think it can be done.
> > 
> > From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> > 
> > If we are trying to filter from the movie props sent to the Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> > 
> > So Imagine a situation where a user doesn't scroll to the bottom and the movie "year" searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> > 
> > So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> > 
> > That's how we can do this
> > 
> > Hope you understand?
> 
> > > > > Does your API have a year query?
> > > > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > > > 
> > > > 
> > > > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> > > 
> > > 
> > > I think it can be done.
> > > From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> > > If we are trying to filter from the movie props sent to the  Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> > > So Imagine a situation where a user doesn't scroll to the bottom and the movie  "year"  searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> > > So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> > > That's how we can do this
> > > Hope you understand?
> > 
> > Solved it 😅😅 will be sending a pull request soon
> 
> Great

I think this problem persists

**Comment by silvareal** [comment]
> > > > > Does your API have a year query?
> > > > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > > > 
> > > > 
> > > > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> > > 
> > > 
> > > I think it can be done.
> > > From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> > > If we are trying to filter from the movie props sent to the Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> > > So Imagine a situation where a user doesn't scroll to the bottom and the movie "year" searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> > > So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> > > That's how we can do this
> > > Hope you understand?
> > 
> > 
> > > > > > Does your API have a year query?
> > > > > > Because the movie props passed to the Movie Component just gives off the data gotten from the fetch done by axios.
> > > > > 
> > > > > 
> > > > > It does not currently. It's a feature on the list. The movies are paginated and not ordered by year so it is kind of difficult getting all movies by a year. All we have for now is the returned movies and the year field
> > > > 
> > > > 
> > > > I think it can be done.
> > > > From what I can see in the code when the user scrolls to the bottom the listIndex which is the page turns 2 so it goes to the next page of the API.
> > > > If we are trying to filter from the movie props sent to the  Movie-list it's hard because it will only return an array of all the movies the user has viewed as the user will have to scroll to the bottom for that props to be updated.
> > > > So Imagine a situation where a user doesn't scroll to the bottom and the movie  "year"  searched for like "2005" Isn't contained in the page one of that API response. The skeleton will load infinitely.
> > > > So we need to find a way to pass all the movies without pagination so we can filter through all the movies.
> > > > That's how we can do this
> > > > Hope you understand?
> > > 
> > > 
> > > Solved it 😅😅 will be sending a pull request soon
> > 
> > 
> > Great
> 
> I think this problem persists

Take your time man, try and wrap your head around the implementation

**Comment by Amenacliff** [comment]
I have been able to implement this feature I can't push to master can I?

Or should I create a new branch?


Because of how the API is structured we will only be able to filter 2020-2018 to access 2017 and below we need to set link index above 100 which I tried to implement but that would break the app.

**Comment by silvareal** [comment]
> I have been able to implement this feature I can't push to master can I?
> 
> Or should I create a new branch?
> 
> Because of how the API is structured we will only be able to filter 2020-2018 to access 2017 and below we need to set link index above 100 which I tried to implement but that would break the app.

Great @Amenacliff , I guess this is your first time contributing to **Open Source**, We are glad to be part of your progress, take a minute and read through this article [Create a push request](https://opensource.com/article/19/7/create-pull-request-github).

Ok, 2020-2018 is ok for now, as not to overload the server.

**Comment by Amenacliff** [comment]
The Files are conflicting 🤦 the build failed it was working perfectly on my pc

**Comment by silvareal** [comment]
> The Files are conflicting 🤦 the build failed it was working perfectly on my pc

If you use the link above in creating a PR,

this should help
`git fetch upstream`
`git merge upstream/master`
then fix conflict and push your branch

**Comment by Amenacliff** [comment]
Build still failing and I did as you said

**Comment by Amenacliff** [comment]
> Build still failing and I did as you said 

Here is the Netlify Build which was successful

https://5ea85d410b95160006989196--gophie.netlify.app/

**Comment by silvareal** [comment]
> > Build still failing and I did as you said
> 
> Here is the Netlify Build which was successful
> 
> https://5ea85d410b95160006989196--gophie.netlify.app/

you were meant to resolve the conflict and push again.

**Comment by Amenacliff** [comment]
> > > Build still failing and I did as you said
> > 
> > Here is the Netlify Build which was successful
> > 
> > https://5ea85d410b95160006989196--gophie.netlify.app/
> 
> you were meant to resolve the conflict and push again.
> 

I did that, it still didn't work
