### ISSUE TITLE
Take a tour

### ISSUE THREAD

**Issue by Dalexz4** [Go-phie/gophie-web#49]
The "take a tour pop-up" should only appear once for every new visitor. Returning visitors shouldn't be getting the same pop-up again.

**Comment by deven96** [comment]
It does pop up only for new users. The button remains there however if a user ever wants to take the tour again

**Comment by deven96** [comment]
What do you think?

**Comment by Dalexz4** [comment]
I still get the pop-up after visiting several times. Perhaps you can check using your normal browser. If the issue persists then we might need to fix it as soon as possible.

**Comment by deven96** [comment]
I will check now
null

**Comment by deven96** [comment]
It doesn't show for old users. Closing this now
