### ISSUE TITLE
Video styling

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie-web#57]
Video streaming implementation needs styling and a way to stop the video (stop button)

**Comment by Amenacliff** [comment]
![Screenshot_2020-04-30-23-29-54-759_com github android 1](https://user-images.githubusercontent.com/47929647/80792909-98e4c300-8b8d-11ea-8d97-42b518fd4fec.jpg)

All of a sudden my I'm out of the list... Is there a problem I can solve or was I removed?
