### ISSUE TITLE
Share movies

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie-web#71]
Create share links to a specific movie

**Comment by SeanDunford** [comment]
https://gophie.cam/Server1/d8007fe0-7989-4c2b-ae0e-af23b5470895

There seems to be a links but they do not work for mobile or web client. Is this a routing issue?

**Comment by deven96** [comment]
The link looks like one for a shared movie. However if that id does not exist i.e d8007fe0-7989-4c2b-ae0e-af23b5470895 then it simply redirects you home

**Comment by SeanDunford** [comment]
Okay, I copied this link from the site for the movie [`Micheal Clayton` ](https://www.imdb.com/title/tt0465538/) so i think the id should be valid.

**Comment by deven96** [comment]
Copying the link won't work. Make use of the share 
button instead. There is some consideration as to why that is so
